### ISSUE TITLE
num_workers参数设置

### ISSUE THREAD

**Issue by yuhaoxu99** [thuml/TimesNet#1]
同学，您好！
    在运行代码的时候，如果按照原本参数num_workers=10运行，会出现以下错误：
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Process finished with exit code 1
    在网上搜索解决办法说把num_workers设置成0，但当我这样运行的时候，对于gpu显存的要求就会特别高，超过24g。请问这样是正常的吗？

**Comment by htg17** [comment]
num_workers可能会影响运行速度，但似乎不会影响显存占用。

不知道您跑的是哪个script？如果是分类任务，因为序列较长，可能显存占用会比较大。

**Comment by yuhaoxu99** [comment]
> num_workers可能会影响运行速度，但似乎不会影响显存占用。
> 
> 不知道您跑的是哪个script？如果是分类任务，因为序列较长，可能显存占用会比较大。

您好，我跑的是python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96 \
  --model TimesNet \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5

**Comment by htg17** [comment]
这个script我跑的结果是显存占用2595MiB，num_workers=0不会改变显存占用。

除了改变num_workers之外，您也可以尝试报错代码里推荐的修改方式，改写run.py：
`def main():`
`   ...`
`if __name__ == '__main__':`
`   main()`

**Comment by yuhaoxu99** [comment]
好的，目前已经解决了！谢谢！
还有一个问题想请教一下您，就是关于AAAI上发表的《Are Transformers Effective for Time Series Forecasting?》这篇论文您有什么看法嘛？

**Comment by htg17** [comment]
我们在论文中涉及了DLinear这一baseline，具体结果可以看我们的论文

**Comment by yuhaoxu99** [comment]
好的，谢谢您！
