### ISSUE TITLE
好奇多变量预测单变量任务的时候timesnet怎么实现的

### ISSUE THREAD

**Issue by wangln19** [thuml/TimesNet#11]
你好！我看了论文之后还不是很清楚多变量预测单变量的时候timesnet怎么实现的。我看time-library里面的代码也没有找到‘MS'情况下的特殊处理，请问可以说明一下吗？

**Comment by wuhaixu2016** [comment]
您好，我们在论文中并没有跑多变量预测单变量的实验，不过这个任务可以通过只在目标变量上计算loss实现，具体请见：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L137-L139

**Comment by wangln19** [comment]
了解了，谢谢!
