### ISSUE TITLE
Motion and trajectory forecasting

### ISSUE THREAD

**Issue by Carrotsniper** [thuml/TimesNet#13]
Thanks for your excellent work which quite helpful.

I am just wondering that if TimesNet can easily be transferred to other tasks with higher dimension input features.
E.g. Human motion prediction (6D with 6 different human joints) or Trajectory prediction (2D with (x,y) coordinates).

Thank you so much if you can share some considerations.

**Comment by wuhaixu2016** [comment]
Hi, it is worth a try.
In our experiments, the UEA classification contains the gesture dataset. TimesNet can deal with this type of data well.
