### ISSUE TITLE
关于不同数据集的训练和验证的命令行参数设定与数据集加载问题

### ISSUE THREAD

**Issue by guilunmeibeautiful** [thuml/TimesNet#14]
您好，以下两个问题：
1、针对不同数据集是否需要改变命令行中如下参数的设置：args.freq, args.embed。因为不同数据集数据的采样频率是不一样的，有的是小时，有的是星期，有的则是15分钟。是否如上这些参数的设定需要根据数据集而改变？TimesNet在不同数据集进行实验的时候是怎样处理这些参数的？
2、data_loader脚本中并没有给出一些数据集(如ECL,Weather等)的数据预处理，如何进行实验？是否是将脚本中的Dataset_Custom类名改为这些数据集(如ECL,Weather等)的名称即可？
请详细解答一下，不胜叨扰，万分感谢！
祝龙年快乐！

**Comment by wuhaixu2016** [comment]
您好，感谢关注
1. 这两个参数的设置你可以仿照timesnet进行，我们在开源代码中提供了完整的运行脚本
2. ECL、Weather这些数据集都被处理成了统一的格式，所以可以公用Dataset_Custom这个类。当然您为了代码可读性，把这个类别改成别的数据集名称也是可以的。

**Comment by guilunmeibeautiful** [comment]
您好，按照脚本中的设置，运行结果不理想，如图所示，确定这个脚本是正确的实验配置么？谢谢

<img width="491" height="708" alt="Image" src="https://github.com/user-attachments/assets/77514a65-db41-49fa-b863-1fe2fdc4a7e6" />

<img width="431" height="29" alt="Image" src="https://github.com/user-attachments/assets/ec1bbb42-df84-4f0e-9e6f-88f0dd1298df" />
