### ISSUE TITLE
A simiar paper with TimesNet 

### ISSUE THREAD

**Issue by EnergyQuantResearch** [thuml/TimesNet#15]
I recently read a paper that is super similar to TimesNet, even dataset for comparision is same and the figures are the same style. 
"Multi-scale transformers with Adaptive Pathways for Time Series Forecasting" 
What is the relation between this and your paper? I didn't see any citation from this paper to timesnet.
Please check, thanks. 
![image](https://github.com/thuml/TimesNet/assets/45356295/5ed4b90c-77b1-4b51-89b3-782e107e1a6c)
![image](https://github.com/thuml/TimesNet/assets/45356295/3f96b933-d751-4446-ba64-e9e824545c01)

**Comment by wuhaixu2016** [comment]
Hi, this paper is from several brilliant researchers. But I do not know until you post this issue. Thanks for your recommendation.
I have read this paper carefully. In the camera-ready version, the authors have included the citations to TimesNet. As for the figure, I am glad to find that the color selection in TimesNet is appreciated and followed by other researchers. Overall, I think this paper is in line with academic norms and proposes a good exploration of adaptive pathways.
