### ISSUE TITLE
关于TimesNet训练时的数据集问题

### ISSUE THREAD

**Issue by TangYH321** [thuml/TimesNet#16]
您好，非常荣幸从您的著作中有所启发，当我复现实验结果时，用TimesNet作分类任务，使用Handwriting数据集，执行sh ./scripts/classification/TimesNet.sh，一直EarlyStopping，是否为数据集格式或者调用数据集的问题，我使用的数据集格式如下
![QQ截图20240306113220](https://github.com/thuml/TimesNet/assets/114870420/7a0b37af-a990-4247-aa58-e2c17080e232)
如果我使用其他非文中所用的数据集进行模型训练时，例如model_id等参数该在哪些方面进行修改？只能导入.ts格式的数据集吗？如果是csv格式的数据集呢？

感谢！

**Comment by wuhaixu2016** [comment]
您好，感谢关注，一直early stop可能是因为数据集的数据量很少或者这个数据集很难优化，可以尝试更多的优化器或者学习率衰减策略。
如果您想使用自己的数据集，需要自己重新写dataloader，目前的code base只支持TS文件
