### ISSUE TITLE
How would I get it to train everything in a csv file with minute by minute data for multiple outputs?

### ISSUE THREAD

**Issue by yfprime** [thuml/TimesNet#17]
What do I set frequency to for 1 minute? Lets say I have a file named dataset.csv (120 columns) with minute-by-minute data, with a column called timestamps with the second timestamp (UNIX time) and another column called percent_change. I want percent_change after 1,2,3,4 and 5 minutes to be predicted, with all the columns in the dataset being input features.
Thank you.

**Comment by wuhaixu2016** [comment]
Hi, you can follow the script in https://github.com/thuml/Time-Series-Library/blob/main/scripts/long_term_forecast/ETT_script/TimesNet_ETTm1.sh
and change the data path to your csv file.

**Comment by yfprime** [comment]
Thank you for the quick response. Where may I select the frequency in this script, specify the timestamp column for being the timestamp column, and specify percent_change for multiple time intervals as the target?
I have 120 inputs features, 5 outputs (percent change over 1,3,5,7 and 10 minutes) with a column named timestamp with the second timestamp (UNIX time) in each minute.)



`python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_96_96 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 64 \
  --d_ff 64 \
  --top_k 5 \
  --itr 1
  
  Which variable stands for specifying the frequency (or is that inferred), the target variables (or the same variable at multiple time frames for my usecase)?
  
  This would use the short-term forecasting model. Does it support minute data?
Sorry for the confusion.

**Comment by Quantbrinx** [comment]
Been looking for minute data support as well. How do we use it for minute data?
