### ISSUE TITLE
关于自建训练集进行训练的问题

### ISSUE THREAD

**Issue by Morphlinggod** [thuml/TimesNet#18]
这个工程对我太有帮助了，非常感谢作者的分享！
想请问一下作者，如果我想做仅关于采样点的时间序列问题，即不包含时间戳，能不能通过修改data_loader来实现？会影响训练的结果吗？目前的情况用自己的数据代入修改weather.csv文件中的‘OT’进行训练。
还有对待Imputation的测试任务的时候，想问一下能不能自己对数据进行mask后进行测试，而不用您在test中编写的测试方式？

**Comment by wuhaixu2016** [comment]
您好，感谢关注与使用
（1）可以修改dataloader，但是如果你的数据是等间隔的话，其实也可以给数据生成一条假的时间戳。一般来说，如果你的数据是强时间依赖的话，可能会有影响，不然不会影响太多。
（2）可以的，您可以根据需要编写测试代码
