### ISSUE TITLE
说实话，评测有问题

### ISSUE THREAD

**Issue by 3186218763** [thuml/TimesNet#22]
A Library for Advanced Deep Time Series Models.
https://github.com/thuml/Time-Series-Library
评测的标准的多。我做水文，风力预测，异常检测就发现这个模型非常难用。不稳定。LSTM混合模型，DLinear，PatchTST相对好用而且效果稳定

**Comment by wuhaixu2016** [comment]
您好，您提到的这个算法库TSLib也是我基于TimesNet的代码写的。

学术论文实验是在相对标准数据集上进行的评测，如果您使用TSLib中的脚本实验的话，可以复现论文结果，所以我觉得TimesNet论文中的评测是可靠的，不过目前大家常见的benchmark确实没有水文、风力相关的。

如果是实际应用的话，我觉得特征工程会更多，如果您方便共享你的应用场景的话，可以给我发邮件wuhx23@mails.tsinghua.edu.cn，我可以给一些调参建议。
