### ISSUE TITLE
关于异常检测任务是如何重构数据的

### ISSUE THREAD

**Issue by Uncle-George-13** [thuml/TimesNet#24]
您好，想请问一下对于异常检测任务的重构误差，其重构的数据是通过什么来实现的

**Comment by wuhaixu2016** [comment]
您好，TimesNet中的异常检测任务是“无监督异常检测”，也就是通过时间序列自己重建自己来判断误差（也可以称为自监督）。

这里的insight在于异常点属于整个数据集中的小样本时间，很难被比较好地重建出来。

**Comment by Uncle-George-13** [comment]
您好，我是想问这样子的问题，就比如是通过这个autoencoder去重建的吗？还是通过什么方法。
