### ISSUE TITLE
关于batch_x , batch_y , batch_x_mark , batch_y_mark含义询问

### ISSUE THREAD

**Issue by yuhaoxu99** [thuml/TimesNet#3]
您好，关于这四个参数在之前学习的时候就有疑问，请问可否解答一下为什么batch分成了x ， y 还有mark呀？以及是怎么通过enumerate(train_loader)得到他们对应的tensor维度呢？可不可以根据exp_long_term_forecasting.py举一下例子呀？我理解enumerate()函数的意思，但不太理解这四个参数的维度以及数值是怎么出来的。

**Comment by yuhaoxu99** [comment]
您好，我这两天仔细思考了一下，有了一个答案，请问您可以看看我的想法是对的吗？
batch_x(32,96,7)维度分别对应(batch , seq_len , feature)，batch_x_mark(32,96,4)维度分别对应(batch , seq_len , times feature)，batch_y(32 ,144,7)维度分别对应(batch , label_len + pred_len , feature)，batch_y_mark(32,144,4)维度分别对应(batch , label_len + pred_len , times feature)，但我还是不太理解这里面的取值是怎么取的，因为我看train_loader里data_x不是(8640 , 7)的维度嘛？若您有空时可否帮忙解答一下呀，万分感谢！

**Comment by wuhaixu2016** [comment]
您好，batch_x和batch_y都是时间序列的原始数据，batch_x_mark和batch_y_mark代表着每个时刻的时间戳信息

**Comment by yuhaoxu99** [comment]
好的明白，谢谢！

**Comment by tongji11** [comment]
好的明白，谢谢！

**Comment by Oten-arch** [comment]
您好，我也有同样的困惑，但我仍没明白batch_x , batch_y , batch_x_mark , batch_y_mark的size是如何得来的，您有空时可否帮忙解答一下，万分感谢！

**Comment by yuhaoxu99** [comment]
> 您好，我也有同样的困惑，但我仍没明白batch_x , batch_y , batch_x_mark , batch_y_mark的size是如何得来的，您有空时可否帮忙解答一下，万分感谢！

其实就是上面我说的那样！

**Comment by Oten-arch** [comment]
不好意思就是看了你所说的还没懂，for batch_idx, (batch_x, batch_y, batch_x_mark, batch_y_mark) in enumerate(train_loader):经过这句代码后为什么batch_x的维度就变成(32,96,7)了呢（batch_y、batch_x_mark、batch_y_mark的疑问也如此）？麻烦可以帮忙解答一下详细过程吗？万分感谢！！

**Comment by yuhaoxu99** [comment]
> 不好意思就是看了你所说的还没懂，for batch_idx, (batch_x, batch_y, batch_x_mark, batch_y_mark) in enumerate(train_loader):经过这句代码后为什么batch_x的维度就变成(32,96,7)了呢（batch_y、batch_x_mark、batch_y_mark的疑问也如此）？麻烦可以帮忙解答一下详细过程吗？万分感谢！！

点进train_loader怎么来的那个函数里，那里边有详细的过程，(32,96,7)分别代表(batch size , seq_len , feature size)。batch_x和batch_y是原始数据，batch_x_mark和batch_y_mark是时间戳，就是把年月日时分秒都embedding过后的数据。

**Comment by guilunmeibeautiful** [comment]
您好，为啥原始数据要分成batch_x和batch_y呢？能否告知具体的含义以及为啥要这样做？ @wuhaixu2016

**Comment by yuhaoxu99** [comment]
> 您好，为啥原始数据要分成batch_x和batch_y呢？能否告知具体的含义以及为啥要这样做？ @wuhaixu2016

x是特征，y是标签

**Comment by guilunmeibeautiful** [comment]
能不能详细点说说，我是新手才接触这个领域，求教了！感谢 @yuhaoxu99
