### ISSUE TITLE
Details about the paper

### ISSUE THREAD

**Issue by navfour** [thuml/TimesNet#6]
We have noticed that in Table 14 of your paper there is a note, “The original paper of N-BEATS (Oreshkin et al., 2019) adopts a special ensemble method to promote the performance.
For fair comparisons, we remove the ensemble and only compare the pure forecasting models.”
We don't quite understand which operation of NBEATS is referred to by "a special ensemble method" here。
Thanks for your guidance

**Comment by wuhaixu2016** [comment]
The N-BEATS ensembles different models trained from different input lengths. You may find more information in the original paper of N-BEATS.

**Comment by navfour** [comment]
感谢您的耐心解答，我理解您这里的意思是不是，在N-BEATS的对照试验中，并没有执行不同windows_size不同stack结构等多超参的bagging操作，而是随机选了一个超参作为起最终结构没有执行遍历多种超参的操作。
