### ISSUE TITLE
Do you still have the original code for the algo?

### ISSUE THREAD

**Issue by LaplaceSingularity** [thuml/TimesNet#7]
Hi! First of all, I want to congratulate you on this amazing piece of work. I wonder if you have the original algo for it? I know that the algorithm was integrated into timeseries-lib but to be honest it will take too much for me to clean the code in order to extract the code :)

**Comment by wuhaixu2016** [comment]
Hi, TSlib is built following the `Factory Method`. If you want to only focus on the TimesNet, you can just delete the other model files. And the start code in TSlib takes the TimesNet as an example. You may find that useful.
