### ISSUE TITLE
About the projection before encoder

### ISSUE THREAD

**Issue by AwesomeSeq** [thuml/TimesNet#8]
in code line 113:

enc_out = self.predict_linear(enc_out.permute(0, 2, 1)).permute(0, 2, 1)  # align temporal dimension

you add a linear layer to project seq_len to (seq_len + pred_len) before feeding it to Time Block. Can you explain why doing this and what it aligns with, thank you.

maybe keeping the original length before encoder and projecting it after encoder is better? I wonder if it will hurt the original temporal information.

**Comment by wuhaixu2016** [comment]
Hi, you may find this issue helpful: https://github.com/thuml/Time-Series-Library/issues/38
