### ISSUE TITLE
Classification Results of Forecasting Models

### ISSUE THREAD

**Issue by xuanmay2701** [thuml/TimesNet#9]
Hi, can you tell me where you get the classification results of forecasting models such as Informer, Autoformer,...?

**Comment by wuhaixu2016** [comment]
Hi, you can follow this script: https://github.com/thuml/Time-Series-Library/blob/main/scripts/classification/Autoformer.sh
The model code can be found here: https://github.com/thuml/Time-Series-Library/blob/main/models/Autoformer.py#L128

**Comment by xuanmay2701** [comment]
Thank you so much!
